$(document).ready(function(){
	const J_REGISTER_SUCCESS_TIP="#registerSuccessTip";
	$(J_USERNAME).blur(function(){
		//验证用户名是否重复
		var username = $(J_USERNAME).val();
		if(username.length<8){
			$(J_USERNAME).addClass(CSS_HAS_ERROR);
			$(J_USERNAME_TIP).text(USERNAME_TOO_SHORT);
			$(J_USERNAME_TIP).addClass(CSS_ALERT_ERROR);
			return;
		}
		else{
			//用户名输入正确（大于8为）则隐藏提示
			$(J_USERNAME_TIP).addClass(CSS_HIDE);
		}
		//验证用户名是否重复
		$.ajax({
			type:METHOD_POST,
			url:USERINFO_MANAGER_REINSPECTION_ACTION,
			data:{"username":username},
			dataType:'text',
			success:function(result){
				if(result == RESULT_FAIL){
					$(J_USERNAME).addClass(CSS_HAS_ERROR);
					$(J_USERNAME_TIP).text(USERNAME_EXIST);
					$(J_USERNAME_TIP).addClass(CSS_ALERT_ERROR);
					$(J_USERNAME_TIP).removeClass(CSS_HIDE);
				}
			}
		});
		
	});
	$(J_USERNAME).focus(function(){
		if($(J_USERNAME).hasClass(CSS_HAS_ERROR)){
			$(J_USERNAME).removeClass(CSS_HAS_ERROR);
			$(J_USERNAME_TIP).removeClass(CSS_ALERT_ERROR);
			$(J_USERNAME_TIP).text(USERNAME_TOO_SHORT);
		}
		$(J_USERNAME_TIP).removeClass(CSS_HIDE);
	});
	$(J_PASSWORD).blur(function(){
		var password = $(J_PASSWORD).val();
		if(password.length<8){
			$(J_PASSWORD).addClass(CSS_HAS_ERROR);
			$(J_PASSWORD_TIP).addClass(CSS_ALERT_ERROR);
			return;
		}
		else{
			//用户名输入正确（大于8为）则隐藏提示
			$(J_PASSWORD_TIP).addClass(CSS_HIDE);
		}
	});
	$(J_PASSWORD).focus(function(){
		if($(J_PASSWORD).hasClass(CSS_HAS_ERROR)){
			$(J_PASSWORD).removeClass(CSS_HAS_ERROR);
		}
		$(J_PASSWORD_TIP).removeClass(CSS_ALERT_ERROR);
		$(J_PASSWORD_TIP).removeClass(CSS_HIDE);
	});
	$(J_REPASSWORD).blur(function(){
		//验证两个密码是否一致
		if($(J_PASSWORD).val() != $(J_REPASSWORD).val()){
			$(J_REPASSWORD).addClass(CSS_HAS_ERROR);
			$(J_REPASSWORD_TIP).removeClass(CSS_HIDE);
		}
	});
	$(J_REPASSWORD).focus(function(){
		if($(J_REPASSWORD).hasClass(CSS_HAS_ERROR)){
			$(J_REPASSWORD).removeClass(CSS_HAS_ERROR);
		}
		$(J_REPASSWORD_TIP).addClass(CSS_HIDE);
		
	});
	$(J_EMAIL).blur(function(){
		//验证邮箱是否符合格式
		var reg=/^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(\.com)+/;
		var email=$(J_EMAIL).val();
		if(!reg.test(email)){
			$(J_EMAIL).addClass(CSS_HAS_ERROR);
			$(J_EMAIL_TIP).removeClass(CSS_HIDE);
		}
	})
	$(J_EMAIL).focus(function(){
		if($(J_EMAIL).hasClass(CSS_HAS_ERROR)){
			$(J_EMAIL).removeClass(CSS_HAS_ERROR)
		}
		$(J_EMAIL_TIP).addClass(CSS_HIDE);
	});
	$(J_SUBMIT).click(function(){
		//如果存在输入格式错误
		if($(J_USERNAME).hasClass(CSS_HAS_ERROR)
				||$(J_USERNAME).hasClass(CSS_HAS_ERROR)
				||$(J_REPASSWORD).hasClass(CSS_HAS_ERROR)
				||$(J_EMAIL).hasClass(CSS_HAS_ERROR))
			return;
		$.ajax({
			type:METHOD_POST,
			url:USERINFO_MANAGER_REGISTER_ACTION,
			data:{'username':$(J_USERNAME).val(),'password':$(J_PASSWORD).val(),'email':$(J_EMAIL).val()},
			dataType:'text',
			success:function(result){
				if(RESULT_SUCCESS == result){
					$(J_REGISTER_SUCCESS_TIP).removeClass(CSS_HIDE);
					setTimeout(function(){
						window.location=USERINFO_MANAGER_INDEX_PAGE;
					},1000);
				}
			}
		});
	});
});