package com.lu.netdisk.entities;
// Generated 2017-8-3 12:58:31 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Fileinfo generated by hbm2java
 */
public class FileInfo implements java.io.Serializable {

	private String username;
	private String filename;
	private int filesize;
	private Date uploaddate;

	public FileInfo() {
	}

	public FileInfo(String username, String filename, int filesize, Date uploaddate) {
		this.username = username;
		this.filename = filename;
		this.filesize = filesize;
		this.uploaddate = uploaddate;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public int getFilesize() {
		return this.filesize;
	}

	public void setFilesize(int filesize) {
		this.filesize = filesize;
	}

	public Date getUploaddate() {
		return this.uploaddate;
	}

	public void setUploaddate(Date uploaddate) {
		this.uploaddate = uploaddate;
	}

}
